//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use chrono::{DateTime, Utc};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "active_course")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub course_id: Option<i64>,
    pub semester_id: Option<i64>,
    pub lecture_id: Option<i64>,
    #[sea_orm(column_type = "Timestamp", nullable)]
    pub activated_at: Option<DateTime<Utc>>,
    #[sea_orm(column_type = "Timestamp")]
    pub updated_at: DateTime<Utc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::courses::Entity",
        from = "Column::CourseId",
        to = "super::courses::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Courses,
    #[sea_orm(
        belongs_to = "super::lectures::Entity",
        from = "Column::LectureId",
        to = "super::lectures::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Lectures,
    #[sea_orm(
        belongs_to = "super::semesters::Entity",
        from = "Column::SemesterId",
        to = "super::semesters::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Semesters,
}

impl Related<super::courses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Courses.def()
    }
}

impl Related<super::lectures::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Lectures.def()
    }
}

impl Related<super::semesters::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Semesters.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}