//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use chrono::{DateTime, Utc};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "course_events")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub course_id: i64,
    pub schedule_id: Option<i64>,
    #[sea_orm(column_type = "Text")]
    pub event_type: String,
    #[sea_orm(column_type = "Text")]
    pub date: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub start_time: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub end_time: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub room: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub building: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub location: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub title: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = "Timestamp")]
    pub created_at: DateTime<Utc>,
    #[sea_orm(column_type = "Timestamp")]
    pub updated_at: DateTime<Utc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::course_schedules::Entity",
        from = "Column::ScheduleId",
        to = "super::course_schedules::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    CourseSchedules,
    #[sea_orm(
        belongs_to = "super::courses::Entity",
        from = "Column::CourseId",
        to = "super::courses::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Courses,
}

impl Related<super::course_schedules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CourseSchedules.def()
    }
}

impl Related<super::courses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Courses.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
