//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use chrono::{DateTime, Utc};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "course_schedules")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub course_id: i64,
    #[sea_orm(column_type = "Text")]
    pub schedule_type: String,
    pub day_of_week: i64,
    #[sea_orm(column_type = "Text")]
    pub start_time: String,
    #[sea_orm(column_type = "Text")]
    pub end_time: String,
    #[sea_orm(column_type = "Text")]
    pub start_date: String,
    #[sea_orm(column_type = "Text")]
    pub end_date: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub room: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub building: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub location: Option<String>,
    pub priority: i64,
    #[sea_orm(column_type = "Timestamp")]
    pub created_at: DateTime<Utc>,
    #[sea_orm(column_type = "Timestamp")]
    pub updated_at: DateTime<Utc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::course_events::Entity")]
    CourseEvents,
    #[sea_orm(
        belongs_to = "super::courses::Entity",
        from = "Column::CourseId",
        to = "super::courses::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Courses,
}

impl Related<super::course_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CourseEvents.def()
    }
}

impl Related<super::courses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Courses.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
