//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use chrono::{DateTime, Utc};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "courses")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub semester_id: i64,
    #[sea_orm(column_type = "Text")]
    pub short_name: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub directory_path: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub toml_path: Option<String>,
    pub exists_on_disk: bool,
    pub toml_exists: bool,
    #[sea_orm(column_type = "Timestamp", nullable)]
    pub last_scanned_at: Option<DateTime<Utc>>,
    pub ects: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub lecturer: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub lecturer_email: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub tutor: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub tutor_email: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub learning_platform_url: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub university: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub location: Option<String>,
    pub is_external: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub original_path: Option<String>,
    pub is_archived: bool,
    pub is_dropped: bool,
    #[sea_orm(column_type = "Timestamp", nullable)]
    pub dropped_at: Option<DateTime<Utc>>,
    pub has_git_repo: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub git_remote_url: Option<String>,
    #[sea_orm(column_type = "Timestamp")]
    pub created_at: DateTime<Utc>,
    #[sea_orm(column_type = "Timestamp")]
    pub updated_at: DateTime<Utc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::active_course::Entity")]
    ActiveCourse,
    #[sea_orm(has_many = "super::course_degree_mappings::Entity")]
    CourseDegreeMappings,
    #[sea_orm(has_many = "super::course_events::Entity")]
    CourseEvents,
    #[sea_orm(has_many = "super::course_possible_categories::Entity")]
    CoursePossibleCategories,
    #[sea_orm(has_many = "super::course_schedules::Entity")]
    CourseSchedules,
    #[sea_orm(
        belongs_to = "super::semesters::Entity",
        from = "Column::SemesterId",
        to = "super::semesters::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Semesters,
    #[sea_orm(has_many = "super::exam_attempts::Entity")]
    ExamAttempts,
    #[sea_orm(has_many = "super::exercises::Entity")]
    Exercises,
    #[sea_orm(has_many = "super::grade_components::Entity")]
    GradeComponents,
    #[sea_orm(has_many = "super::grades::Entity")]
    Grades,
    #[sea_orm(has_many = "super::holiday_exceptions::Entity")]
    HolidayExceptions,
    #[sea_orm(has_many = "super::lectures::Entity")]
    Lectures,
    #[sea_orm(has_many = "super::platform_course_links::Entity")]
    PlatformCourseLinks,
    #[sea_orm(has_many = "super::slides::Entity")]
    Slides,
    #[sea_orm(has_many = "super::todos::Entity")]
    Todos,
}

impl Related<super::active_course::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ActiveCourse.def()
    }
}

impl Related<super::course_degree_mappings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CourseDegreeMappings.def()
    }
}

impl Related<super::course_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CourseEvents.def()
    }
}

impl Related<super::course_possible_categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CoursePossibleCategories.def()
    }
}

impl Related<super::course_schedules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CourseSchedules.def()
    }
}

impl Related<super::semesters::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Semesters.def()
    }
}

impl Related<super::exam_attempts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExamAttempts.def()
    }
}

impl Related<super::exercises::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Exercises.def()
    }
}

impl Related<super::grade_components::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GradeComponents.def()
    }
}

impl Related<super::grades::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Grades.def()
    }
}

impl Related<super::holiday_exceptions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HolidayExceptions.def()
    }
}

impl Related<super::lectures::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Lectures.def()
    }
}

impl Related<super::platform_course_links::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlatformCourseLinks.def()
    }
}

impl Related<super::slides::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Slides.def()
    }
}

impl Related<super::todos::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Todos.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
