//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use chrono::{DateTime, Utc};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "course_degree_mappings")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub course_id: i64,
    pub degree_id: i64,
    pub area_id: i64,
    pub ects_override: Option<i64>,
    #[sea_orm(column_type = "Timestamp")]
    pub created_at: DateTime<Utc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::courses::Entity",
        from = "Column::CourseId",
        to = "super::courses::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Courses,
    #[sea_orm(
        belongs_to = "super::degree_areas::Entity",
        from = "Column::AreaId",
        to = "super::degree_areas::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    DegreeAreas,
    #[sea_orm(
        belongs_to = "super::degrees::Entity",
        from = "Column::DegreeId",
        to = "super::degrees::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Degrees,
}

impl Related<super::courses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Courses.def()
    }
}

impl Related<super::degree_areas::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DegreeAreas.def()
    }
}

impl Related<super::degrees::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Degrees.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}