//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use chrono::{DateTime, Utc};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "degrees")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text")]
    pub r#type: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub university: String,
    pub total_ects_required: i64,
    pub is_active: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub start_date: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub expected_end_date: Option<String>,
    #[sea_orm(column_type = "Timestamp")]
    pub created_at: DateTime<Utc>,
    #[sea_orm(column_type = "Timestamp")]
    pub updated_at: DateTime<Utc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::course_degree_mappings::Entity")]
    CourseDegreeMappings,
    #[sea_orm(has_many = "super::course_possible_categories::Entity")]
    CoursePossibleCategories,
    #[sea_orm(has_many = "super::degree_areas::Entity")]
    DegreeAreas,
}

impl Related<super::course_degree_mappings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CourseDegreeMappings.def()
    }
}

impl Related<super::course_possible_categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CoursePossibleCategories.def()
    }
}

impl Related<super::degree_areas::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DegreeAreas.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}