//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use chrono::{DateTime, Utc};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "degree_areas")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub degree_id: i64,
    #[sea_orm(column_type = "Text")]
    pub category_name: String,
    pub required_ects: i64,
    pub counts_towards_gpa: bool,
    pub display_order: i64,
    #[sea_orm(column_type = "Timestamp")]
    pub created_at: DateTime<Utc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::course_degree_mappings::Entity")]
    CourseDegreeMappings,
    #[sea_orm(has_many = "super::course_possible_categories::Entity")]
    CoursePossibleCategories,
    #[sea_orm(
        belongs_to = "super::degrees::Entity",
        from = "Column::DegreeId",
        to = "super::degrees::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Degrees,
}

impl Related<super::course_degree_mappings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CourseDegreeMappings.def()
    }
}

impl Related<super::course_possible_categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CoursePossibleCategories.def()
    }
}

impl Related<super::degrees::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Degrees.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}