//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use chrono::{DateTime, Utc};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "exam_attempts")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub course_id: i64,
    pub attempt_number: i64,
    #[sea_orm(column_type = "Text")]
    pub exam_date: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub exam_type: Option<String>,
    #[sea_orm(column_type = "Double", nullable)]
    pub grade: Option<f64>,
    pub passed: bool,
    pub grade_id: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub notes: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub location: Option<String>,
    #[sea_orm(column_type = "Timestamp")]
    pub created_at: DateTime<Utc>,
    #[sea_orm(column_type = "Timestamp")]
    pub updated_at: DateTime<Utc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::courses::Entity",
        from = "Column::CourseId",
        to = "super::courses::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Courses,
    #[sea_orm(
        belongs_to = "super::grades::Entity",
        from = "Column::GradeId",
        to = "super::grades::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Grades,
}

impl Related<super::courses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Courses.def()
    }
}

impl Related<super::grades::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Grades.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}