//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use chrono::{DateTime, Utc};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "exercises")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub course_id: i64,
    pub exercise_number: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub title: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub assignment_file_path: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub solution_directory_path: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub due_date: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub submission_date: Option<String>,
    #[sea_orm(column_type = "Double", nullable)]
    pub points_earned: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub points_total: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub grade: Option<f64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub feedback: Option<String>,
    pub is_submitted: bool,
    pub is_graded: bool,
    #[sea_orm(column_type = "Timestamp")]
    pub created_at: DateTime<Utc>,
    #[sea_orm(column_type = "Timestamp")]
    pub updated_at: DateTime<Utc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::courses::Entity",
        from = "Column::CourseId",
        to = "super::courses::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Courses,
    #[sea_orm(has_many = "super::todos::Entity")]
    Todos,
}

impl Related<super::courses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Courses.def()
    }
}

impl Related<super::todos::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Todos.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}