//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use chrono::{DateTime, Utc};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "grades")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub course_id: i64,
    #[sea_orm(column_type = "Double")]
    pub grade: f64,
    #[sea_orm(column_type = "Text")]
    pub grading_scheme: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub original_grade: Option<f64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub original_scheme: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub conversion_table: Option<String>,
    pub is_final: bool,
    pub passed: bool,
    pub attempt_number: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub exam_date: Option<String>,
    #[sea_orm(column_type = "Timestamp")]
    pub recorded_at: DateTime<Utc>,
    #[sea_orm(column_type = "Timestamp")]
    pub updated_at: DateTime<Utc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::courses::Entity",
        from = "Column::CourseId",
        to = "super::courses::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Courses,
    #[sea_orm(has_many = "super::exam_attempts::Entity")]
    ExamAttempts,
    #[sea_orm(has_many = "super::grade_components::Entity")]
    GradeComponents,
}

impl Related<super::courses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Courses.def()
    }
}

impl Related<super::exam_attempts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExamAttempts.def()
    }
}

impl Related<super::grade_components::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GradeComponents.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}