//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use chrono::{DateTime, Utc};
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "grade_components")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub course_id: i64,
    pub grade_id: Option<i64>,
    #[sea_orm(column_type = "Text")]
    pub component_name: String,
    #[sea_orm(column_type = "Double")]
    pub weight: f64,
    #[sea_orm(column_type = "Double", nullable)]
    pub points_earned: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub points_total: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub grade: Option<f64>,
    pub is_bonus: bool,
    #[sea_orm(column_type = "Double", nullable)]
    pub bonus_points: Option<f64>,
    pub is_completed: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub due_date: Option<String>,
    #[sea_orm(column_type = "Timestamp", nullable)]
    pub completed_at: Option<DateTime<Utc>>,
    #[sea_orm(column_type = "Timestamp")]
    pub created_at: DateTime<Utc>,
    #[sea_orm(column_type = "Timestamp")]
    pub updated_at: DateTime<Utc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::courses::Entity",
        from = "Column::CourseId",
        to = "super::courses::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Courses,
    #[sea_orm(
        belongs_to = "super::grades::Entity",
        from = "Column::GradeId",
        to = "super::grades::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Grades,
}

impl Related<super::courses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Courses.def()
    }
}

impl Related<super::grades::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Grades.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
