//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use chrono::{DateTime, Utc};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "holiday_exceptions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub holiday_id: i64,
    pub course_id: i64,
    #[sea_orm(column_type = "Timestamp")]
    pub created_at: DateTime<Utc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::courses::Entity",
        from = "Column::CourseId",
        to = "super::courses::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Courses,
    #[sea_orm(
        belongs_to = "super::holidays::Entity",
        from = "Column::HolidayId",
        to = "super::holidays::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Holidays,
}

impl Related<super::courses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Courses.def()
    }
}

impl Related<super::holidays::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Holidays.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}