//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use chrono::{DateTime, Utc};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "holidays")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub start_date: String,
    #[sea_orm(column_type = "Text")]
    pub end_date: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub university: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub holiday_type: String,
    #[sea_orm(column_type = "Timestamp")]
    pub created_at: DateTime<Utc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::holiday_exceptions::Entity")]
    HolidayExceptions,
}

impl Related<super::holiday_exceptions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HolidayExceptions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
