//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use chrono::{DateTime, Utc};
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "lectures")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub course_id: i64,
    pub lecture_number: i64,
    #[sea_orm(column_type = "Text")]
    pub schedule_type: String,
    #[sea_orm(column_type = "Text")]
    pub date: String,
    #[sea_orm(column_type = "Text")]
    pub start_time: String,
    #[sea_orm(column_type = "Text")]
    pub end_time: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub room: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub building: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub location: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub title: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub notes: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub slides_covered: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub git_commit_sha: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub notes_file_path: Option<String>,
    #[sea_orm(column_type = "Timestamp")]
    pub created_at: DateTime<Utc>,
    #[sea_orm(column_type = "Timestamp")]
    pub updated_at: DateTime<Utc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::active_course::Entity")]
    ActiveCourse,
    #[sea_orm(
        belongs_to = "super::courses::Entity",
        from = "Column::CourseId",
        to = "super::courses::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Courses,
    #[sea_orm(has_many = "super::slides::Entity")]
    Slides,
    #[sea_orm(has_many = "super::todos::Entity")]
    Todos,
}

impl Related<super::active_course::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ActiveCourse.def()
    }
}

impl Related<super::courses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Courses.def()
    }
}

impl Related<super::slides::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Slides.def()
    }
}

impl Related<super::todos::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Todos.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
