//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod active_course;
pub mod course_degree_mappings;
pub mod course_events;
pub mod course_possible_categories;
pub mod course_schedules;
pub mod courses;
pub mod degree_areas;
pub mod degrees;
pub mod exam_attempts;
pub mod exercises;
pub mod grade_components;
pub mod grades;
pub mod holiday_exceptions;
pub mod holidays;
pub mod lectures;
pub mod platform_accounts;
pub mod platform_course_links;
pub mod semesters;
pub mod slides;
pub mod todos;
