//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use chrono::{DateTime, Utc};
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "platform_accounts")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text")]
    pub platform_type: String,
    #[sea_orm(column_type = "Text")]
    pub platform_url: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub university: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub username: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub token: Option<String>,
    pub is_active: bool,
    #[sea_orm(column_type = "Timestamp", nullable)]
    pub last_sync_at: Option<DateTime<Utc>>,
    #[sea_orm(column_type = "Timestamp")]
    pub created_at: DateTime<Utc>,
    #[sea_orm(column_type = "Timestamp")]
    pub updated_at: DateTime<Utc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::platform_course_links::Entity")]
    PlatformCourseLinks,
}

impl Related<super::platform_course_links::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlatformCourseLinks.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
