//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use chrono::{DateTime, Utc};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "platform_course_links")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub course_id: i64,
    pub platform_account_id: i64,
    #[sea_orm(column_type = "Text")]
    pub platform_course_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub platform_course_url: Option<String>,
    pub auto_sync_exercises: bool,
    pub auto_sync_slides: bool,
    pub auto_sync_announcements: bool,
    #[sea_orm(column_type = "Timestamp", nullable)]
    pub last_synced_at: Option<DateTime<Utc>>,
    #[sea_orm(column_type = "Timestamp")]
    pub created_at: DateTime<Utc>,
    #[sea_orm(column_type = "Timestamp")]
    pub updated_at: DateTime<Utc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::courses::Entity",
        from = "Column::CourseId",
        to = "super::courses::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Courses,
    #[sea_orm(
        belongs_to = "super::platform_accounts::Entity",
        from = "Column::PlatformAccountId",
        to = "super::platform_accounts::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    PlatformAccounts,
}

impl Related<super::courses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Courses.def()
    }
}

impl Related<super::platform_accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlatformAccounts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}