//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::active_course::Entity as ActiveCourse;
pub use super::course_degree_mappings::Entity as CourseDegreeMappings;
pub use super::course_events::Entity as CourseEvents;
pub use super::course_possible_categories::Entity as CoursePossibleCategories;
pub use super::course_schedules::Entity as CourseSchedules;
pub use super::courses::Entity as Courses;
pub use super::degree_areas::Entity as DegreeAreas;
pub use super::degrees::Entity as Degrees;
pub use super::exam_attempts::Entity as ExamAttempts;
pub use super::exercises::Entity as Exercises;
pub use super::grade_components::Entity as GradeComponents;
pub use super::grades::Entity as Grades;
pub use super::holiday_exceptions::Entity as HolidayExceptions;
pub use super::holidays::Entity as Holidays;
pub use super::lectures::Entity as Lectures;
pub use super::platform_accounts::Entity as PlatformAccounts;
pub use super::platform_course_links::Entity as PlatformCourseLinks;
pub use super::semesters::Entity as Semesters;
pub use super::slides::Entity as Slides;
pub use super::todos::Entity as Todos;
