//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use chrono::{DateTime, Utc};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "semesters")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text")]
    pub r#type: String,
    pub number: i64,
    #[sea_orm(column_type = "Text")]
    pub directory_path: String,
    pub exists_on_disk: bool,
    #[sea_orm(column_type = "Timestamp", nullable)]
    pub last_scanned_at: Option<DateTime<Utc>>,
    #[sea_orm(column_type = "Text", nullable)]
    pub start_date: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub end_date: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub default_location: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub university: Option<String>,
    pub is_current: bool,
    pub is_archived: bool,
    #[sea_orm(column_type = "Timestamp")]
    pub created_at: DateTime<Utc>,
    #[sea_orm(column_type = "Timestamp")]
    pub updated_at: DateTime<Utc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::active_course::Entity")]
    ActiveCourse,
    #[sea_orm(has_many = "super::courses::Entity")]
    Courses,
}

impl Related<super::active_course::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ActiveCourse.def()
    }
}

impl Related<super::courses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Courses.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
