//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use chrono::{DateTime, Utc};
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "slides")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub course_id: i64,
    #[sea_orm(column_type = "Text")]
    pub file_name: String,
    #[sea_orm(column_type = "Text")]
    pub file_path: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub file_hash: Option<String>,
    pub slide_number: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub title: Option<String>,
    pub page_count: Option<i64>,
    pub is_covered: bool,
    pub covered_in_lecture_id: Option<i64>,
    #[sea_orm(column_type = "Timestamp", nullable)]
    pub file_modified_at: Option<DateTime<Utc>>,
    #[sea_orm(column_type = "Timestamp")]
    pub scanned_at: DateTime<Utc>,
    #[sea_orm(column_type = "Timestamp")]
    pub updated_at: DateTime<Utc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::courses::Entity",
        from = "Column::CourseId",
        to = "super::courses::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Courses,
    #[sea_orm(
        belongs_to = "super::lectures::Entity",
        from = "Column::CoveredInLectureId",
        to = "super::lectures::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Lectures,
}

impl Related<super::courses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Courses.def()
    }
}

impl Related<super::lectures::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Lectures.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
