//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use chrono::{DateTime, Utc};
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "todos")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub course_id: Option<i64>,
    pub lecture_id: Option<i64>,
    pub exercise_id: Option<i64>,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub due_date: Option<String>,
    pub completed: bool,
    #[sea_orm(column_type = "Timestamp", nullable)]
    pub completed_at: Option<DateTime<Utc>>,
    pub auto_clear: bool,
    #[sea_orm(column_type = "Timestamp")]
    pub created_at: DateTime<Utc>,
    #[sea_orm(column_type = "Timestamp")]
    pub updated_at: DateTime<Utc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::courses::Entity",
        from = "Column::CourseId",
        to = "super::courses::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Courses,
    #[sea_orm(
        belongs_to = "super::exercises::Entity",
        from = "Column::ExerciseId",
        to = "super::exercises::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Exercises,
    #[sea_orm(
        belongs_to = "super::lectures::Entity",
        from = "Column::LectureId",
        to = "super::lectures::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Lectures,
}

impl Related<super::courses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Courses.def()
    }
}

impl Related<super::exercises::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Exercises.def()
    }
}

impl Related<super::lectures::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Lectures.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
